import { Metadata } from "next";

export const metadata: Metadata = {
  title: {
    template: "%s | Codevolution",
    default: "Next js tutorial",
  },
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <header style={{ backgroundColor: "lightblue", padding: "1rem" }}>
          <div
            style={{
              display: "flex",
              justifyContent: "space-between",
              alignItems: "center",
            }}
          >
            <span style={{ fontWeight: "bolder" }}>LOGO</span>
            <ul
              style={{ listStyleType: "none", display: "flex", gap: "1.5rem" }}
            >
              <li>
                <a
                  href="#"
                  style={{ textDecoration: "none", color: "GrayText" }}
                >
                  About
                </a>
              </li>
              <li>
                <a
                  href="#"
                  style={{ textDecoration: "none", color: "GrayText" }}
                >
                  Work
                </a>
              </li>
              <li>
                <a
                  href="#"
                  style={{ textDecoration: "none", color: "GrayText" }}
                >
                  Contact
                </a>
              </li>
            </ul>
          </div>
        </header>
        {children}
        <footer
          style={{
            backgroundColor: "ghostwhite",
            padding: "1rem",
            textAlign: "center",
          }}
        >
          <div>Copyright@ 2025. All rights reserved </div>
        </footer>
      </body>
    </html>
  );
}
